### ISSUE TITLE
error cb.apply is not a function

### ISSUE THREAD

**Issue by allaura-dev** [nodejs/help#2874]
* **Node.js Version**:
{
  npm: '4.6.1',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '83',
  napi: '6',
  nghttp2: '1.41.0',
  node: '14.6.0',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.38.1',
  v8: '8.4.371.19-node.12',
  zlib: '1.2.11'
}
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime

I can not do anything with my npm as I keep receiving "error cb.apply is not a function"
- I have tried to clear the cache but it can not due to this error
- I removed everything to do with does and the tools it downloads with it and reinstalled with windows up to date then rebooted but still receive the same error
-i have tried npm doctor but failed due to this error
- I have checked the path is correct for nodejs and node_modules
How can i fix this issue?

Error chache information

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\allie\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@4.6.1
3 info using node@v12.18.3
4 verbose config Skipping project config: C:\Users\allie/.npmrc. (matches userconfig)
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose stack TypeError: cb.apply is not a function
7 verbose stack     at C:\Users\allie\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
7 verbose stack     at FSReqCallback.oncomplete (fs.js:169:5)
8 verbose cwd C:\Users\allie
9 verbose Windows_NT 10.0.19041
10 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\allie\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
11 verbose node v12.18.3
12 verbose npm  v4.6.1
13 error cb.apply is not a function
14 verbose exit [ 1, true ]

**Comment by travisredington** [comment]
Yeah having the same issue with node 12.18.3 & 14.6.0

**Comment by allaura-dev** [comment]
I solved it on both my computers. One needed more work on it.
Option 1:
Follow this directory 
C:\Users\(your username)\AppData\Roaming
Delete the npm folder and if there is one mom cache folder.
Run npm clean cache —force ( — force is now required to clean cache)
You should be good now if not do option 2.

Option 2:
Follow this directory 
C:\Users\(your username)\AppData\Roaming
Delete the npm folder and if there is one mom cache folder.
Run npm clean cache —force ( — force is now required to clean cache)
Make sure everything to do with Nodejs is deleted and uninstalled.
Reinstall Nodejs.
You should be good now.

**Comment by travisredington** [comment]
great, will try sometime soon, thanks!

**Comment by MattKehrls** [comment]
First Option worked great for me, thanks!

**Comment by blackthought286** [comment]
worked. Thanks

**Comment by travisredington** [comment]
Yeah, option 1 worked for me as well! Thanks! ( using v14.6.0 )

**Comment by aldanin** [comment]
First option worked for me.
Thanks a bunch!

**Comment by shuiche-it** [comment]
mac how to do?

**Comment by Ivo-Balbaert** [comment]
Thank you very much!!

**Comment by AHassanSOS** [comment]
This error is new. It happens if I try to install npm twice in the row.

**Comment by kulor** [comment]
I found resolve in downgrading to Node 12.18.2 as the `graceful-fs` that was being used was hard linked by an older dependency of mine. For the lazy (Linux):

```
NODE_VERSION=12.18.2
curl -sSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v$NODE_VERSION-linux-x64/bin/node
```

**Comment by ridhi-mago** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

First option worked!! Thanks!

**Comment by HarelM** [comment]
Can the solution provided by @allaura-dev added to nodejs installer in case of major version upgrade?
I updated nodejs today and ran into the same issue just to find out someone already found a solution... :-(

**Comment by yasarui** [comment]
First option worked for me. Thanks a lot

**Comment by lumosmind** [comment]
First option worked. Thanks a lot

**Comment by Naz786** [comment]
Guys if you are trying to follow the answer above and you cannot access the 'C:\Users(your username)\AppData\Roaming' folder, then go to 'this PC' in file explorer, search 'npm', you will see folders 'npm' or 'npm-cache' which are inside '...AppData\Roaming\'  folders. Delete these by accessing the path to '...\AppData\Roaming\'.

**Comment by allaura-dev** [comment]
> Can the solution provided by @allaura-dev added to nodejs installer in case of major version upgrade?
> 
> I updated nodejs today and ran into the same issue just to find out someone already found a solution... :-(

I agree. I was working on a new project and the same thing happened.

**Comment by teknorix1** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

You saved me, Thanks

**Comment by gigamonkey** [comment]
> mac how to do?

It seems that you can use `npm root -g` to find the directory which is not `AppData\Roaming` on a mac. Though in my case it turned out I had an old `~/node_modules/` lying around causing problems. When I deleted it this problem went away.

**Comment by blackraspberry08** [comment]
For me, it worked when I reinstalled `graceful-fs` by running `npm install graceful-fs --save-dev` as suggested by Giovanni Esposito here: https://stackoverflow.com/questions/63054545/all-my-react-native-projects-shows-error-typeerror-cb-apply-is-not-a-function/63054816#63054816

**Comment by SrikanthCM** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one npm cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

Thank you very much option 1 helped a 2 hour problem

**Comment by xaviergmail** [comment]
> I found resolve in downgrading to Node 12.18.2 as the `graceful-fs` that was being used was hard linked by an older dependency of mine. For the lazy (Linux):
> 
> ```
> NODE_VERSION=12.18.2
> curl -sSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v$NODE_VERSION-linux-x64/bin/node
> ```

For me, this seemed to be the only solution on WSL. WSL2 / debian sid

**Comment by detj** [comment]
Getting this exact error on macOS 10.15.6

> It seems that you can use npm root -g to find the directory which is not AppData\Roaming on a mac. Though in my case it turned out I had an old ~/node_modules/ lying around causing problems. When I deleted it this problem went away.

I didn't have any duplicate `node_modules` at `npm -g root`. I deleted all global packages except `npm`. But this problem still exists.

I faced this while trying to serve a static website

```sh
$ ls
public
$ npx serve public/
npm ERR! cb.apply is not a function
```

**Comment by bricechilders** [comment]
First option worked for me, though for some reason I had to do 

npm cache clean --force

**Comment by seyedk1** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one npm cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

great. This worked for me. Thanks.

**Comment by negue** [comment]
I only had to delete the `npm` Folder =>
`C:\Users\(your username)\AppData\Roaming\npm\node_modules\npm`

Then it worked again.

Deleting all files ... just took way to long 😁

**Comment by ajaysingh9835** [comment]
option 2 worked absolutly fine for me ! great

**Comment by Tuckett45** [comment]
Neither of them have worked for me. Still getting this error

"Vue CLI v4.5.4
✨  Creating project in C:\Users\TAustin\maevnsite.
�  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

npm ERR! Windows_NT 10.0.18363
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TAustin\\node_modules\\npm\\bin\\npm-cli.js" "install" "--loglevel" "error"
npm ERR! node v14.8.0
npm ERR! npm  v3.10.10

npm ERR! cb.apply is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\TAustin\maevnsite\npm-debug.log
 ERROR  command failed: npm install --loglevel error".

Not sure what else I should do

**Comment by aleen42** [comment]
Have the same issume under https://github.com/aleen42/PersonalWiki/runs/1039544585?check_suite_focus=true, it seems that `graceful-fs@1.x` has broken under node@12.8.3 or node @14.8.0

**Comment by Sford4** [comment]
I was able to just switch node version with nvm, `nvm use 10`

**Comment by madhu-ounce** [comment]
Thanks it is worked for me

**Comment by Naz786** [comment]
How do I unsubscribe from this thread, anyone?

**Comment by addaleax** [comment]
@Naz786 There’s a link on the right-hand side in the github interface:

![Screenshot from 2020-09-09 13-09-20](https://user-images.githubusercontent.com/899444/92591235-cceb9580-f29d-11ea-8b3d-92d6fab85af4.png)

If you’re using email notifications, which it looks like you might be doing, there’s also an “unsubscribe” link at the bottom of the email (in the footer).

**Comment by Naz786** [comment]
Thank you. 😊

**Comment by HumayounBaig** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one npm cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

this saved my day was stuck for about 2-3 days now thanks @allaura-dev

**Comment by andy380743909** [comment]
I have this problem when installing gitbook, and I install a lower version(version 10, the latest is version 14), the problem just goes away.

**Comment by keeev** [comment]
I didn't have the problem with gitbook but [this guide](https://flaviocopes.com/cb-apply-not-a-function/) by flavioscopes helped me by commenting out the lines 59-62 in the affected polyfill.js file: 

```
/*   fs.stat = statFix(fs.stat)
  fs.fstat = statFix(fs.fstat)
  fs.lstat = statFix(fs.lstat)
 */
```

**Comment by rishabhshairy** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one npm cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.


First Option Worked for me.
Thanks

**Comment by erichlof** [comment]
Will this whole issue be fixed by the next Node version?  Before I found this page, I killed 2 hours wondering why nothing was working.

**Comment by detj** [comment]
Can confirm that this issue still persists in `12.8.4`.

```
$ npx gatsby-cli new .
npm ERR! cb.apply is not a function
```

**Comment by Legion003** [comment]
> Have the same issume under https://github.com/aleen42/PersonalWiki/runs/1039544585?check_suite_focus=true, it seems that `graceful-fs@1.x` has broken under `node@12.8.3` or `node@14.8.0`. To work around this, I have used https://github.com/actions/setup-node to setup [`node@13.x`](https://github.com/aleen42/PersonalWiki/runs/1039609197?check_suite_focus=true) and [`node@10.x`](https://github.com/aleen42/PersonalWiki/runs/1039583366?check_suite_focus=true), both of them worked.

13.5.0 worked!!!! Thank you!!

**Comment by jckling** [comment]
I have this problem with gitbook, and solutions didn't work for me. I found this guide 👇  and solved the problem.

- [How I fixed a "cb.apply is not a function" error while using Gitbook](https://flaviocopes.com/cb-apply-not-a-function/)

**Comment by popstheman** [comment]
@blackraspberryyy solution worked for me. Thanks

**Comment by jdnva** [comment]
Node v12.18.4 works

**Comment by deepak19k96** [comment]
thank you very much
first option works for me. I didn't try 2 option

**Comment by mapoart** [comment]
Hey guys! I had this issue when I installed the second version of node/npm. Uninstalled, and now works. Maybe the issue is one cache for different versions of npm and the structure is different? c:\Users\<username>\AppData\Roaming\ has 2 folders npm and npm-cache. Anyways uninstalling one of the nodes worked for me.

**Comment by arun9989** [comment]
Install latest version and clear the cache.

**Comment by logical-programmers** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one npm cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

thq very much worked first option

**Comment by gutijuarez** [comment]
i resolved my problem with the solution of @allaura-dev 
![react working](https://user-images.githubusercontent.com/19228301/94955652-85c57e80-04b0-11eb-85c5-1847afc76929.png)

**Comment by MaMrEzO** [comment]
Be aware that may you have silently two installation of nmp like mine! One update installation and an old one by yarn.
you can find out by reading npm error logs, in this case you will see two different npm version number in error logs and `npm version` command.
```bash
❯ cat /home/{user}/.npm/_logs/2020-10-03T05_34_01_238Z-debug.log
.
.
.
9 verbose stack     at /home/{user}/.config/yarn/global/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
9 verbose stack     at FSReqCallback.oncomplete (fs.js:178:5)
10 verbose cwd /.../Projects/.../new-react-prj
11 verbose Linux 5.8.12-arch1-1
12 verbose argv "/usr/bin/node" "/home/{user}/.config/yarn/global/node_modules/npx/node_modules/npm/bin/npm-cli.js" "install" "proton-native-cli@latest" "--global" "--prefix" "/home/{user}/.npm/_npx/136164" "--loglevel" "error" "--json"
13 verbose node v14.12.0
14 verbose npm  v5.1.0 #######<<<<< HERE
.
.
.
```
AND
```bash
❯ npm version
{
npm: '6.14.7',
ares: '1.16.1',
brotli: '1.0.9',
cldr: '37.0',
icu: '67.1',
llhttp: '2.1.2',
modules: '83',
napi: '7',
nghttp2: '1.41.0',
node: '14.12.0',
openssl: '1.1.1g',
tz: '2019c',
unicode: '13.0',
uv: '1.39.0',
v8: '8.4.371.19-node.16',
zlib: '1.2.11'
}
```

**Comment by detj** [comment]
Still facing this issue on `macOS 10.15.7` & `node v12.19.0`

To reproduce, run this
```
$ node --version
$ v12.19.0

$ npm --version
$ 6.14.8

$ npx create-react-app --help
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/detj/.npm/_logs/2020-10-08T05_11_53_938Z-debug.log
Install for [ 'create-react-app@latest' ] failed with code 1
```

**Comment by MaMrEzO** [comment]
@detj can you provide content of `/Users/detj/.npm/_logs/2020-10-08T05_11_53_938Z-debug.log` file too?

**Comment by detj** [comment]
@MaMrEzO Sorry, missed to include the logs. Here it is.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/detj/n/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'create-react-app@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/detj/.npm/_npx/98890',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.19.0
4 verbose npm-session 2f07a770c08dd5c1
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/create-react-app 583ms (from cache)
8 silly pacote tag manifest for create-react-app@latest fetched in 603ms
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:285:20
9 verbose stack     at FSReqCallback.oncomplete (fs.js:169:5)
10 verbose cwd /private/tmp
11 verbose Darwin 19.6.0
12 verbose argv "/Users/detj/n/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "install" "create-react-app@latest" "--global" "--prefix" "/Users/detj/.npm/_npx/98890" "--loglevel" "error" "--json"
13 verbose node v12.19.0
14 verbose npm  v6.9.0
15 error cb.apply is not a function
16 verbose exit [ 1, true ]
```

Now, I'm surprised why is npm v6.9.0 being used when I have 6.14.8 installed.

**Comment by detj** [comment]
@MaMrEzO Fixed it. `npx` was symlinked to a location in `/usr/local/lib/node_modules/npm`. Which was of version 6.9.0. this might have happened during one of my earlier node/npm installation/re-installation session.

I have cleaned everything up now and `npx create-react-app --hep` works. All the binaries are correctly pointing to their respective installed versions.

thanks.

**Comment by DariusKopka** [comment]
Options 1 work very fine, thank you.

**Comment by tanjilk** [comment]
if i run the `npm clean cache —force` it appears that
```  
npm WARN npm npm does not support Node.js v12.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10
, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN npm npm does not support Node.js v12.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10
, 11.
npm WARN npm You can find the latest version at https://nodejs.org/

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    completion, config, create, ddp, dedupe, deprecate,
    dist-tag, docs, doctor, edit, explore, get, help,
    help-search, hook, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, profile, prune, publish, rb, rebuild, repo, restart,
    root, run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Aluno\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.2.0-next.1 C:\Users\Aluno\Desktop\node js\node_modules\npm  
```

**Comment by PoojaDurgad** [comment]
@tanjilk  - npm will not remove data by itself: the cache will grow as new packages are installed. hence `npm clean cache —force`
delete all data out of the cache folder. if it doesn't work then you can manually delete the folder %appdata%\npm-cache and 
then install the `npm install npm@latest -g` hope it may help

**Comment by PoojaDurgad** [comment]
@allaura-dev  - is this still an issue?

**Comment by Glen-Bai** [comment]
I got the same issue on macOS.
Here is my solution.
Besides the error message above, there are other tips:
npm ERR! A complete log of this run can be found in:
npm ERR! /Users/xxx/.npm/_logs/2020-10-20T07_41_00_394Z-debug.log
Open the file of xxx-debug.log:
///
verbose cli '/usr/local/Cellar/node/14.12.0/bin/node',
verbose cli '/Users/xxx/node_modules/.bin/npm', <-------!!! wrong
verbose cli 'install',6 verbose cli '--loglevel',
verbose cli 'error',6 verbose cli '@vue/cli-plugin-babel@~4.5.0',
verbose cli '@vue/cli-plugin-eslint@~4.5.0',
verbose cli '@vue/cli-service@~4.5.0',
verbose cli '--save-dev'6 verbose cli ]
info using npm@6.5.0 <-------!!! wrong
info using node@v14.12.0
///
I found the npm version and path are wrong.
I open the path of the npm of log file.
cd /Users/xxx/node_modules/.bin/
then i run the command of ls -al.
///
lrwxr-xr-x npm -> ../npm/bin/npm-cli.js
lrwxr-xr-x npx -> ../npm/bin/npx-cli.js
///The links above point to wrong paths.
The correct paths are :
lrwxr-xr-x npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x npx -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
After recorrecting these links. vue works well.

**Comment by ALVSoft** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one npm cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

Option 1 worked for me!!
thanks a lot!!

**Comment by piskernik** [comment]
On a Mac I had to do:
```
rm -r ~/.node_modules_global/
sudo npm cache clean --force
sudo rm -r /usr/local/bin/npm
sudo rm -rf /usr/local/lib/node_modules  
brew uninstall node
brew install node
```
npm version was 4.1.2
node version was 15.0.1

**Comment by szebenyib** [comment]
For me it was (Arch up-to-date):

```
rm -rf .node_modules_global
npm cache clean --force
```

**Comment by tanjilk** [comment]
> @tanjilk - npm will not remove data by itself: the cache will grow as new packages are installed. hence `npm clean cache —force`
> delete all data out of the cache folder. if it doesn't work then you can manually delete the folder %appdata%\npm-cache and
> then install the `npm install npm@latest -g` hope it may help
I deleted the npm-cache folder in %appdata% but if i run `npm install npm@latest -g` appears that.   
```
C:\Users\Aluno\AppData\Roaming>npm install npm@latest -g
npm WARN npm npm does not support Node.js v12.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10
, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN npm npm does not support Node.js v12.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10
, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aluno\AppData\Roaming\npm-cache\_logs\2020-11-09T09_03_49_
523Z-debug.log```

**Comment by tanjilk** [comment]
I am trying to install the `request` module with npm and appears that   
```C:\Users\Aluno\Desktop\node js>npm install node js
npm WARN npm npm does not support Node.js v12.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10
, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN npm npm does not support Node.js v12.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10
, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aluno\AppData\Roaming\npm-cache\_logs\2020-11-09T09_06_38_
065Z-debug.log```

**Comment by PoojaDurgad** [comment]
@tanjilk - can you try installing latest version of node.

**Comment by nhhockeyplayer** [comment]
still an issue 

node version 14.2.0
npm 6.1.4.8

cleaned cache with  --force

no remedy

**Comment by nhhockeyplayer** [comment]
so Im just tryign to get my 50k lines of production code running on angular v11

UPDATE... (had to sneak back down to node v10 to get this past the callback cb.apply SPOOF)
ok so I had to uninstall node.js v15
install node.js verion v10
then do a massive upgrade/install of all my package.json packages as originally attempted
it completed fine no cb.apply err
then I uninstalled node 10
then I installed node v15

kind of a yuck but it worked something internally i binding to an earlier version of npm tripping up my big angular 11 upgrade

my angular code installed and built beautifully without a hitch upgraded to angular v11

**Comment by nikopolidi** [comment]
I was at node v12.18.4 when having such issues.
Fixed by upgrading node to v12.20.0.

**Comment by Infinitay** [comment]
I started having this issue when trying to create a react app. I have tried both options 1 and 2 as provided by allaura-dev, but none of them worked for me.

I am still having issues on the current node.js version
node: `15.3.0`
npm: `7.0.15`

Here is my log:

> 0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v15.3.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [
6 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
6 verbose cli   'C:\\Users\\infinity\\Documents\\Code\\node_modules\\npm\\bin\\npm-cli.js',
6 verbose cli   'install',
6 verbose cli   '--save',
6 verbose cli   '--save-exact',
6 verbose cli   '--loglevel',
6 verbose cli   'error',
6 verbose cli   'react',
6 verbose cli   'react-dom',
6 verbose cli   'react-scripts',
6 verbose cli   'cra-template'
6 verbose cli ]
7 info using npm@6.6.0
8 info using node@v15.3.0
9 verbose npm-session aeddb80927b099fa
10 silly install loadCurrentTree
11 silly install readLocalPackageData
12 verbose stack TypeError: cb.apply is not a function
12 verbose stack     at C:\Users\infinity\Documents\Code\node_modules\npm\node_modules\graceful-fs\polyfills.js:285:20
12 verbose stack     at FSReqCallback.oncomplete (node:fs:193:5)
13 verbose cwd C:\Users\infinity\Documents\Code\React\my-react-app
14 verbose Windows_NT 10.0.19041
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\infinity\\Documents\\Code\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "--save-exact" "--loglevel" "error" "react" "react-dom" "react-scripts" "cra-template"
16 verbose node v15.3.0
17 verbose npm  v6.6.0
18 error cb.apply is not a function
19 verbose exit [ 1, true ]

**Comment by RajibulAlam** [comment]
I have tried a lot of solutions from different posts and google pages and nothing worked for me.

I ended up cleaning all traces of node, nodejs, and npm. May need some manual force remove after the purge call. And then installed using nvm.

https://linuxize.com/post/how-to-install-node-js-on-ubuntu-20-04/#installing-nodejs-and-npm-using-nvm

And it resolved the issue for me. It got the nodejs v 15.4.0 and the compatible version of npm 7.0.15 ( before using apt-get it was installing npm 6.9.0)

**Comment by fatimashahid101** [comment]
first option worked.
thankyou!

**Comment by sage-gu** [comment]
I am using 10.12.0
use nvm fixed it
nvm uninstall 10.12.0
nvm install 10.12.0

**Comment by gnazaryan** [comment]
This works for me from: https://github.com/jprichardson/node-fs-extra/issues/703
Im just download zip https://github.com/isaacs/node-graceful-fs to /usr/local/lib/node_modules/
and extract with name graceful-fs

**Comment by haroldao** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one npm cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

Thanks it works for me 😉

**Comment by kryalama** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one npm cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

Both the options didnot work for me. Downgrading the node version to v12.6.0 fixed the issue.

**Comment by SimonEast** [comment]
Why is this bug still occurring? Do all developers have to resort to manual workarounds and edit their filesystem directly?

I just installed the latest version of NodeJS on Windows and getting this error, presumably because something is wrong with my npm cache, from a previous version. I guess I'll have to manually delete it like others here. But would be nice to get a proper fix.

**Comment by ck1ldn** [comment]
Option 1 worked perfectly!
manually deleting the npm from an old version seemed to do the trick
Option 1:
Follow this directory
C:\Users(your username)\AppData\Roaming
Delete the npm folder and if there is one npm cache folder.
Run npm clean cache —force ( — force is now required to clean cache)

**Comment by billyrtc13** [comment]
node v-15.8.0
cb.apply is not a function

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npx\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'create-react-app@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\Billy\\AppData\\Roaming\\npm-cache\\_npx\\8048',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v15.8.0
4 verbose npm-session c3d3d5dc7393cfd5
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/create-react-app 186ms (from cache)
8 silly pacote tag manifest for create-react-app@latest fetched in 222ms
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at C:\Program Files\nodejs\node_modules\npx\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
9 verbose stack     at FSReqCallback.oncomplete (node:fs:197:5)
10 verbose cwd C:\www\Billy\Planos
11 verbose Windows_NT 10.0.19042
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npx\\node_modules\\npm\\bin\\npm-cli.js" "install" "create-react-app@latest" "--global" "--prefix" "C:\\Users\\Billy\\AppData\\Roaming\\npm-cache\\_npx\\8048" "--loglevel" "error" "--json"
13 verbose node v15.8.0
14 verbose npm  v5.1.0
15 error cb.apply is not a function
16 verbose exit [ 1, true ]

**Comment by super-kamil** [comment]
Same for me... a soon as you are using nvm after switching the version npx does not work anymore.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\info\\AppData\\Roaming\\npm\\node_modules\\npx\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@backstage/create-app@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\info\\AppData\\Roaming\\npm-cache\\_npx\\32888',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v14.15.4
4 verbose npm-session 760bafac7cb2c2a7
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@backstage%2fcreate-app 425ms (from cache)
8 silly pacote tag manifest for @backstage/create-app@latest fetched in 476ms
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at C:\Users\info\AppData\Roaming\npm\node_modules\npx\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
9 verbose stack     at FSReqCallback.oncomplete (fs.js:184:5)
10 verbose cwd C:\Users\info\Projects\brueckner\tests\backstage
11 verbose Windows_NT 10.0.19041
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\info\\AppData\\Roaming\\npm\\node_modules\\npx\\node_modules\\npm\\bin\\npm-cli.js" "install" "@backstage/create-app@latest" "--global" "--prefix" "C:\\Users\\info\\AppData\\Roaming\\npm-cache\\_npx\\32888" "--loglevel" "error" "--json"
13 verbose node v14.15.4
14 verbose npm  v5.1.0
15 error cb.apply is not a function
16 verbose exit [ 1, true ]
```

**Comment by Nargle30** [comment]
Had the same issue on my Mac, was resolved by installing graceful-fs (npm install graceful-fs --save-dev)

But.. when I build the project in AppCenter I still see the exact same issue. 
Does anyone experience anything like this?

**Comment by ndhanh96** [comment]
for UBUNTU and MAC:
```
go to the outside folder of your volumes, not the root folder, don't install create-react-app global.
run this : npm install react-app , it will make a node_modules folder.
and then you can run npx create-react-app my-app
```

**Comment by ShubhamPatel0736** [comment]
i don't have this appdata folder

**Comment by russhuq** [comment]
> Guys if you are trying to follow the answer above and you cannot access the 'C:\Users(your username)\AppData\Roaming' folder, then go to 'this PC' in file explorer, search 'npm', you will see folders 'npm' or 'npm-cache' which are inside '...AppData\Roaming' folders. Delete these by accessing the path to '...\AppData\Roaming'.


I actually had to do this hard search to get the npm and npm-cache files removed. Now it's working. Thank you!

**Comment by corymalcolmtaylor** [comment]
To get past this bug I had to uninstall and reinstall node in addition to removing the npm, npm-cache and node_modules folders mentioned.

**Comment by thekerker** [comment]
> I got the same issue on macOS.
> Here is my solution.
> Besides the error message above, there are other tips:
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/xxx/.npm/_logs/2020-10-20T07_41_00_394Z-debug.log
> Open the file of xxx-debug.log:
> ///
> verbose cli '/usr/local/Cellar/node/14.12.0/bin/node',
> verbose cli '/Users/xxx/node_modules/.bin/npm', <-------!!! wrong
> verbose cli 'install',6 verbose cli '--loglevel',
> verbose cli 'error',6 verbose cli '@vue/cli-plugin-babel@~4.5.0',
> verbose cli '@vue/cli-plugin-eslint@~4.5.0',
> verbose cli '@vue/cli-service@~4.5.0',
> verbose cli '--save-dev'6 verbose cli ]
> info using npm@6.5.0 <-------!!! wrong
> info using node@v14.12.0
> ///
> I found the npm version and path are wrong.
> I open the path of the npm of log file.
> cd /Users/xxx/node_modules/.bin/
> then i run the command of ls -al.
> ///
> lrwxr-xr-x npm -> ../npm/bin/npm-cli.js
> lrwxr-xr-x npx -> ../npm/bin/npx-cli.js
> ///The links above point to wrong paths.
> The correct paths are :
> lrwxr-xr-x npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
> lrwxr-xr-x npx -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
> After recorrecting these links. vue works well.

Oh holy cow, this is exactly what I needed to fix the issue. Wow, thank you!

**Comment by robertmazzo** [comment]
I deleted npm and npm-cache as suggested, but the clean command which worked for me was "**npm cache clean --force**"

**Comment by gbalduzzi** [comment]
Just wanna add the after struggling with this problem for hours, on my react-native project I only managed to fix it thanks to this stack overflow answer: https://stackoverflow.com/questions/63214997/typeerror-cb-apply-is-not-a-function

Add this to your `package.json`:

```
"resolutions": {
    "graceful-fs": "4.2.4"
  },
```

then run `yarn` or `npm run install`. Hope it helps someone else struggling considering this thread if one of the first showing up when googling and that stackoverflow is a bit more hidden.

**Comment by Myriame-2020** [comment]
> I solved it on both my computers. One needed more work on it.
> Option 1:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one npm cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> You should be good now if not do option 2.
> 
> Option 2:
> Follow this directory
> C:\Users(your username)\AppData\Roaming
> Delete the npm folder and if there is one mom cache folder.
> Run npm clean cache —force ( — force is now required to clean cache)
> Make sure everything to do with Nodejs is deleted and uninstalled.
> Reinstall Nodejs.
> You should be good now.

Thank you ! the second option worked !

**Comment by Pzixel** [comment]
Facing this issue right now on freshly installed Node 16.0. Nothing listed above helped so far :(

**Comment by YATACOBLAS** [comment]
Great, Option 1 Work for me

**Comment by matronator** [comment]
> I found resolve in downgrading to Node 12.18.2 as the `graceful-fs` that was being used was hard linked by an older dependency of mine. For the lazy (Linux):
> 
> ```
> NODE_VERSION=12.18.2
> curl -sSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v$NODE_VERSION-linux-x64/bin/node
> ```

Or if you use nvm for managing different node versions, you can do this instead:

```
nvm install 12.18.2
nvm use 12.18.2
```

This fixed it as well (on macOS).

If you don't have nvm installed I highly recommend getting it, because these sorts of issues pop up quite often and with nvm you can easily change your node versions without overwriting your current installation. Instructions how to install: https://nodejs.org/en/download/package-manager/#nvm

**Comment by youssefbenfarhat** [comment]
Still not working with v14.16.1

**Comment by charithar** [comment]
Option 1 worked nicely!

**Comment by RomeshKTripathi** [comment]
I faced this exact problem first time and I tried most of the methods available here at last 

Step 1: Deleted npm folder from :C:\Users\'user-name'\AppData\Roaming\
Step 2: Run command: npm clean cache -force
Step 3: Run command: npm install create-react-app -g
Step 4: Move in your target forder and Run command: npx create-react-app appName

I hope this will solve your issue 99.9%.

**Comment by evilrussian** [comment]
Workaround in node:v14.16.0
```bash
$ yarn global add gitbook-cli@2.2.0
$ gitbook fetch 3.2.3
```

**Comment by markmackend** [comment]
> 
> 
> I found resolve in downgrading to Node 12.18.2 as the `graceful-fs` that was being used was hard linked by an older dependency of mine. For the lazy (Linux):
> 
> ```
> NODE_VERSION=12.18.2
> curl -sSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v$NODE_VERSION-linux-x64/bin/node
> ```

This worked for me! Thanks!

**Comment by Ahmmad86** [comment]
> I solved it on both my computers. One needed more work on it. Option 1: Follow this directory C:\Users(your username)\AppData\Roaming Delete the npm folder and if there is one npm cache folder. Run npm clean cache —force ( — force is now required to clean cache) You should be good now if not do option 2.
> 
> Option 2: Follow this directory C:\Users(your username)\AppData\Roaming Delete the npm folder and if there is one mom cache folder. Run npm clean cache —force ( — force is now required to clean cache) Make sure everything to do with Nodejs is deleted and uninstalled. Reinstall Nodejs. You should be good now.

the same thing happen with me , am used ur solve and all thing gets right

**Comment by JEF2050** [comment]
thanks!!, the firts option  worked to me...:)

**Comment by RyanLiu0235** [comment]
Listen to me, download and install the newest LTS version NodeJS, and the world turns out just fine.

**Comment by mycoberago** [comment]
This worked for me and I hope it's helpful...

Tried everything suggested but none worked.

I noticed that since I am using NVM, everything points to **/Users/{username}/.nvm/...etc** when checking for node, npm and npx versions.  However, when executing **npx create-react-app** command, the error points to **/Users/{username}/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18**

It's using the correct node version through NVM but it's reverting to using the wrong node_modules folder as if it's the default.  I **_deleted the node_modules folder and it all worked perfect_**.

**Comment by yangqiang1** [comment]
我试过了所有方法还是不行

**Comment by yangqiang1** [comment]
finally,I did it by nvm use old version eg 14.18.2, it is unuseful by using node(the latest version),

**Comment by yangqiang1** [comment]
> 我试过了所有方法还是不行

finally,I did it by nvm use old version eg 14.18.2, it is unuseful by using node(the latest version)

**Comment by yangqiang1** [comment]
> 我试过了所有方法还是不行

finally,I did it by nvm using old version eg 14.18.2, it is unuseful by using node(the latest version).

**Comment by Fahad16301139** [comment]
thanks!first option worked for me!!

**Comment by bobcorp99** [comment]
I had the same problem, tried it out, and It works, THANK YOU!

**Comment by arashi-dev** [comment]
**Another Solution**

I don't know how it worked but I deleted folder `C:\Users\[username]\AppData\Local\Yarn` and repaired the nodejs through the exe file and it got fixed. now I can use the latest version of npm.

**Comment by erg** [comment]
for macos:

`which npx`
/Users/erg/.nvm/versions/node/v18.2.0/bin/npx

nuke it all:
`rm -rf ~/.nvm/versions`

**Comment by Disciplined-22** [comment]
Thank you

**Comment by shgit-dev** [comment]
> I solved it on both my computers. One needed more work on it. Option 1: Follow this directory C:\Users(your username)\AppData\Roaming Delete the npm folder and if there is one npm cache folder. Run npm clean cache —force ( — force is now required to clean cache) You should be good now if not do option 2.
> 
> Option 2: Follow this directory C:\Users(your username)\AppData\Roaming Delete the npm folder and if there is one mom cache folder. Run npm clean cache —force ( — force is now required to clean cache) Make sure everything to do with Nodejs is deleted and uninstalled. Reinstall Nodejs. You should be good now.

Thanks @allaura-dev  First Option works for me.

**Comment by 1akshat** [comment]
> > mac how to do?
> 
> It seems that you can use `npm root -g` to find the directory which is not `AppData\Roaming` on a mac. Though in my case it turned out I had an old `~/node_modules/` lying around causing problems. When I deleted it this problem went away.

Worked for me,

**Comment by simon-os** [comment]
Unfortunately, none of the solutions listed above worked for me. I found out that in my case the problem was in system PATH variable. I have two profiles on windows, so I had two entries in the PATH variable pointing to the same place. It looked like this: 

C:\Users\{USER_1}\AppData\Roaming\npm
C:\Users\{USER_2}\AppData\Roaming\npm

Once I removed one of the path entries, it worked! To be precise, I removed the one that pointed to the directory of user, that wasn't for work

**Comment by wuqingabc** [comment]
> > mac how to do?
> 
> It seems that you can use `npm root -g` to find the directory which is not `AppData\Roaming` on a mac. Though in my case it turned out I had an old `~/node_modules/` lying around causing problems. When I deleted it this problem went away.

Save my day, thank you.

**Comment by plasticalligator** [comment]
Whoever closed this issue without actually fixing the problem deserves to have their legs broken. 
That is all. You disgust me.
